# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
builds:
  -
    ldflags:
      - -s -w -X "main.version={{.Env.RELEASE_VERSION}}"
    main: main.go
    binary: tgswitch
    goos:
      - darwin
      - linux
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
checksum:
  name_template: '{{ .ProjectName }}_{{.Env.RELEASE_VERSION}}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
archives:
  -
    name_template: '{{ .ProjectName }}_{{.Env.RELEASE_VERSION}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
